package gg.rsmod.net.codec.login

/**
 * @author Tom <rspsmods@gmail.com>
 */
enum class LoginResultType(
    val id: Int,
) {
    AD_COUNTDOWN_THEN_END(0),
    COULD_NOT_DISPLAY_AD(1),
    LOGGED_IN(2),
    INVALID_CREDENTIALS(3),
    ACCOUNT_BANNED(4),
    ALREADY_ONLINE(5),
    REVISION_MISMATCH(6),
    WORLD_FULL(7),
    SERVER_OFFLINE(8),
    LOGIN_LIMIT_EXCEEDED(9),
    BAD_SESSION_ID(10),
    WEAK_PASSWORD(11),
    MEMBER_WORLD(12),
    COULD_NOT_COMPLETE_LOGIN(13),
    SERVER_UPDATE(14),
    MAX_ATTEMPTS(16),
    INVALID_ACCOUNT_REQUESTED(17),
    ACCOUNT_LOCKED(18),
    FULLSCREEN_MEMBERS_ONLY(19),
    INVALID_LOGIN_SERVER(20),
    WORLD_SWITCH(21),
    MALFORMED_PACKET(22),
    NO_REPLY_FROM_LOGIN_SERVER(23),
    ERROR_LOADING_PROFILE(24),
    IP_BANNED(26),
}
